apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
  annotations:
    # Tells KServe's internal agent to associate these credentials with the model downloader
    serving.kserve.io/s3-secret-uuid: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIARGAXZ3DH6JE6LWOJ"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_DEFAULT_REGION: "ap-south-1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: default
secrets:
  - name: s3-secret
